# Site settings
title: 五更记
description: 行做笔，心当墨。
baseurl: ""
url: "https://yourusername.github.io"
author: Your Name
email: your.email@example.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title.html

# Pagination
paginate: 6
paginate_path: "/page/:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Theme settings
theme_settings:
  # Color scheme
  primary_color: "#ffcc00"
  text_color: "#333333"
  background_color: "#ffffff"
  
  # Typography
  heading_font: "Playfair Display, serif"
  body_font: "Source Sans Pro, sans-serif"
  
  # Hero section
  hero_title: "探索·旅行·新知"
  hero_subtitle: "One day, I will be able to see the whole world."
  hero_image: "/assets/images/hero-bg.jpg"
  
  # Social links
  social:
    github: "bearfm"
    twitter: ""
    instagram: ""
    email: "hello@z.org"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
    values:
      layout: "default"